config/routes.rb
Rails.application.routes.draw do
  root to: 'reports#index'
  resources :reports
  resources :pictures
  resources :report_types
  resources :companies
  resources :users

  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/controllers/report_types_controller.rb
class ReportTypesController < ApplicationController
  before_action :set_report_type, only: [:show, :edit, :update, :destroy]

  def index
    @report_types = ReportType.all
  end

  def show
  end

  def new
    @report_type = ReportType.new
  end

  def edit
  end

  def create
    @report_type = ReportType.new(report_type_params)

    respond_to do |format|
      if @report_type.save
        format.html { redirect_to @report_type, notice: 'Report type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @report_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @report_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @report_type.update(report_type_params)
        format.html { redirect_to @report_type, notice: 'Report type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @report_type.destroy
    respond_to do |format|
      format.html { redirect_to report_types_url }
      format.json { head :no_content }
    end
  end

  private
    def set_report_type
      @report_type = ReportType.find(params[:id])
    end

    def report_type_params
      params.require(:report_type).permit(:name, :private)
    end
end

app/helpers/report_types_helper.rb
module ReportTypesHelper
end

app/views/report_types/_form.html.erb
<%= simple_form_for(@report_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :private %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/report_types/edit.html.erb
<h1>Editing report_type</h1>
<%= link_to 'Retour', report_types_path, class: 'btn btn-default' %>

<%= render 'form' %>

app/views/report_types/index.html.erb
<h1>Listing des types de signalement</h1>
<%= link_to 'Retour', reports_path, class: 'btn btn-default' %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Private</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @report_types.each do |report_type| %>
      <tr>
        <td><%= report_type.name %></td>
        <td><%= report_type.private %></td>
        <td>
          <%= link_to 'Editer', edit_report_type_path(report_type), class: 'btn btn-success' %>
          <%= link_to 'Supprimer', report_type, method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: 'btn btn-warning'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Créer un type de signalement', new_report_type_path, class: 'btn btn-success' %>

app/views/report_types/new.html.erb
<h1>Créer un type de signalement</h1>
<%= link_to 'Retour', report_types_path, class: 'btn btn-default' %>

<%= render 'form' %>

app/views/report_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @report_type.name %>
</p>

<p>
  <strong>Private:</strong>
  <%= @report_type.private %>
</p>

<%= link_to 'Editer', edit_report_type_path(@report_type) %> |
<%= link_to 'Retour', report_types_path %>