config/routes.rb
Rails.application.routes.draw do
  root to: 'reports#index'
  resources :reports
  resources :pictures
  resources :report_types
  resources :companies
  resources :users

  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :path, AttachmentUploader
  belongs_to :report
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render action: 'show', status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:path)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= simple_form_for(@picture) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :path %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pictures/create.html.erb
<h1>Picture#create</h1>
<p>Find me in app/views/picture/create.html.erb</p>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <thead>
    <tr>
      <th>Path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.path %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Path:</strong>
  <%= @picture.path %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>